version: "1"

node-image: &use-node-image
  image: hub.docker.target.com/node:20.13.1-alpine

pull_request: &on-pull-request
  ruleset:
    event: pull_request

push_to_main: &on_push_to_main
  ruleset:
    event: push
    branch: main

stages:
  setup:
    steps:
      - name: setup
        <<: [*on-pull-request, *use-node-image]
        commands:
          - corepack enable && corepack prepare
          - pnpm install

  format:
    needs: setup
    steps:
      - name: format
        <<: [*on-pull-request, *use-node-image]
        commands:
          - corepack enable && corepack prepare
          - pnpm format

  publish:
    steps:
      - name: populate_docker_credentials
        image: docker.target.com/managed/vela-plugins/artifactory-managed-auth:v1.4.0@sha256:4396697f30b3e6e42255350f19cbd95d0db8452b118e6fd444f2b7e3929b1a1f
        parameters:
          auth_server: https://artifactorytokenmanager.prod.target.com

      - name: publish
        image: docker.target.com/vela-plugins/kaniko:latest
        pull: always
        <<: [*on_push_to_main]
        parameters:
          repo: "docker.target.com/managed/tech2elevate/${VELA_REPO_NAME}"
          tags:
            - "b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}"
          snapshot_mode: redo

  build:
    needs: setup
    steps:
      - name: build
        <<: [*on-pull-request, *use-node-image]
        commands:
          - corepack enable && corepack prepare
          - NEXT_TELEMETRY_DISABLED=1 pnpm build
